fixed bug and add device
nihui/opencv-mobile pull request #138
Opened 2024-08-05 06:44 UTC by Zheng-Bicheng

2024-08-05 06:47 UTC, Zheng-Bicheng commented
目前的方式使用 `rk_aiq_uapi2_sysctl_getBindedSnsEntNmByVd` 来获取 sns_entity_name。这是一个过时的方法，在最新的 RV1106 SDK 上会出现错误，这里改成了使用 `rk_aiq_uapi2_sysctl_enumStaticMetasByPhyId` 来获取 sns_entity_name。

2024-08-05 06:48 UTC, Zheng-Bicheng commented
在配置 AIQ 前，需要先设置系统 HDR_MODE 为 1，具体原因未知，RK 的 IPC 例程内就这么干的

2024-08-05 06:49 UTC, Zheng-Bicheng commented
在初始化sense之前需要调用 `rk_aiq_uapi2_sysctl_preInit_devBufCnt` 来设置设备的缓冲区数量

2024-08-05 06:50 UTC, Zheng-Bicheng commented
新增了对 LockzhinerVisionModule 设备的适配

2024-08-05 06:50 UTC, Zheng-Bicheng commented
@nihui

2024-08-05 06:56 UTC, csukuangfj commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        if (strncmp(buf, "LockzhinerVisionModule", 12) == 0)
```suggestion
        if (strncmp(buf, "LockzhinerVisionModule", 22) == 0)
```
`LockzhinerVisionModule` 有 22 个字符.

上面的例子, `Luckfox Pico` 有12个字符，所以用了12.
不能直接 copy 的.

2024-08-05 06:57 UTC, csukuangfj commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        if (strncmp(buf, "LockzhinerVisionModule", 12) == 0)
```suggestion
        else if (strncmp(buf, "LockzhinerVisionModule", 12) == 0)
```

可以加个 else

2024-08-05 07:00 UTC, Zheng-Bicheng commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        if (strncmp(buf, "LockzhinerVisionModule", 12) == 0)
用 `sizeof` 代替了一下

2024-08-05 07:00 UTC, Zheng-Bicheng commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        if (strncmp(buf, "LockzhinerVisionModule", 12) == 0)
done

2024-08-05 07:07 UTC, Zheng-Bicheng commented
顺便在文档中添加了对 Lockfox 和 LockzhinerVisionModule 的编译教程

2024-08-05 07:17 UTC, csukuangfj requested changes

2024-08-05 07:17 UTC, csukuangfj commented on README.md
> +mkdir -p build && cd build
原来的也没问题，对不对？（即不改也没关系)

2024-08-05 07:17 UTC, csukuangfj commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        if (strncmp(buf, "Luckfox Pico", sizeof("Luckfox Pico")) == 0)
`sizeof("Luckfox Pico")` 是不是把后面的 `\0` 也包含进去了？
原来的 12 是不是一点问题都没有，不需要改？

2024-08-05 07:19 UTC, Zheng-Bicheng commented on README.md
> +mkdir -p build && cd build
感觉整合到一起好看一点，其他开源项目好像也都这么干的，需要改回去吗？

2024-08-05 07:20 UTC, Zheng-Bicheng commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        if (strncmp(buf, "Luckfox Pico", sizeof("Luckfox Pico")) == 0)
确实忽略了这个问题，本意是不希望手动计算，比较麻烦

2024-08-05 07:20 UTC, Zheng-Bicheng commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        if (strncmp(buf, "Luckfox Pico", sizeof("Luckfox Pico")) == 0)
我加个-1修复下吧

2024-08-07 01:33 UTC, csukuangfj approved these changes

2024-08-07 03:05 UTC, nihui commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +typedef XCamReturn (*PFN_rk_aiq_uapi2_sysctl_preInit_devBufCnt)(const char* sns_ent_name, const char* dev_ent, int buf_cnt);
不要补那么多注释啊 qaq

2024-08-07 03:05 UTC, nihui commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +            fprintf(stderr, "ERROR: aiq_static_info.sensor_info.phyId is %d\n", aiq_static_info.sensor_info.phyId);
如果不存在 rk_aiq_uapi2_sysctl_enumStaticMetasByPhyId，那么回退到 rk_aiq_uapi2_sysctl_getBindedSnsEntNmByVd

2024-08-07 03:05 UTC, nihui commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +            XCamReturn ret = rk_aiq_uapi2_sysctl_preInit_scene(aiq_static_info.sensor_info.sensor_name, "normal", "day");
如果没有 rk_aiq_uapi2_sysctl_preInit_scene，回退到 rk_aiq_uapi2_sysctl_preInit_scene

2024-08-08 02:51 UTC, nihui commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        rk_aiq_uapi2_sysctl_preInit_devBufCnt(sns_entity_name, dev_ent, 2);
```suggestion
        rk_aiq_uapi2_sysctl_preInit_devBufCnt(sns_entity_name, "rkraw_rx", 2);
```

2024-08-08 02:51 UTC, nihui commented on highgui/src/capture_v4l2_rk_aiq.cpp
> +        fprintf(stderr, "ID: %d, sensor_name is %s, iqfiles is %s\n", cam_id, sns_entity_name, iq_file_dir);
```suggestion
        // char iq_file_dir[] = "/oem/usr/share/iqfiles";
        // fprintf(stderr, "ID: %d, sensor_name is %s, iqfiles is %s\n", cam_id, sns_entity_name, iq_file_dir);
```

2024-08-09 01:50 UTC, merged

2024-08-09 01:50 UTC, nihui commented
Thanks for your contribution !