support imshow in gui on windows
nihui/opencv-mobile pull request #142
Opened 2024-08-07 01:41 UTC by futz12

支持以GUI的方法显示图片。

相比opencv原版的imshow，本PR更好的支持了高分屏。支持滚动条以便显示高分辨率图片，窗口大小可自由调节。

效果演示：
![9ccfba62d1a1db9159468a9053ac741c](https://github.com/user-attachments/assets/aa5300b3-6703-46a4-9795-e827bcf60f1b)

2024-08-07 02:44 UTC, nihui commented
bmpWnd.cpp 改为 display_win32.cpp，然后加在cmakelists.txt里头，参考 https://github.com/nihui/opencv-mobile/pull/137 的更改

2024-08-07 06:42 UTC, futz12 commented
改好了，但是需要注意的是PR的逻辑和opencv原版并不相同。无论是否waitkey窗口都会立即显示。同名窗口并不会被后面显示的内容替换。

2024-08-08 02:53 UTC, nihui commented
> 改好了，但是需要注意的是PR的逻辑和opencv原版并不相同。无论是否waitkey窗口都会立即显示。同名窗口并不会被后面显示的内容替换。

啊这，如果做成同名字窗口更新显示困难吗，因为很可能会用在摄像头显示里面

2024-08-11 17:20 UTC, futz12 commented
目前而言，本PR已经和Windows上的OpenCV几乎完全一致。
已知不一致之处：
1. 窗口能够自由调整大小与滚动
2. 与原版OpenCV不同，本PR的imshow能够在子线程上正常调用，同时设计中考虑到一定的线程安全（但是不建议在多线程同时waitkey，这种行为是未定义的）。

2024-08-15 07:02 UTC, nihui requested changes
新增的 h cpp 源码开头，参考其他填充 copyright 信息

2024-08-15 07:11 UTC, futz12 reviewed
已更改

2024-09-07 13:28 UTC, merged

2024-09-07 13:28 UTC, nihui commented
Thanks for your contribution !